import requests
from datetime import datetime, timezone

SOURCE = "https://raw.githubusercontent.com/its-tujo/Blocklist-for-Far-Right-and-Anti-Semitic-Websites/main/BlockList.txt"


def normalize(line: str):
    line = line.strip()
    if not line or line.startswith("#"):
        return None
    return line.replace("https://", "").replace("http://", "").strip("/")


def load_old():
    try:
        with open("BlockList.txt", "r", encoding="utf-8") as f:
            return {l.strip() for l in f.readlines() if l.strip()}
    except FileNotFoundError:
        return set()


def write_file(path, content):
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(content))


def main():
    raw = requests.get(SOURCE, timeout=30).text.splitlines()

    new_domains = {normalize(l) for l in raw}
    new_domains = {d for d in new_domains if d}

    old_domains = load_old()

    added = sorted(new_domains - old_domains)
    removed = sorted(old_domains - new_domains)

    all_domains = sorted(new_domains)

    # uBlock rules
    ublock_rules = [f"||{d}^" for d in all_domains]

    # LeechBlock rules
    leechblock = sorted(
        {d for d in all_domains} |
        {f"*.{d}" for d in all_domains}
    )

    # -------------------------
    # BlockList (source of truth)
    # -------------------------
    write_file("BlockList.txt", all_domains)

    # -------------------------
    # uBlock with header
    # -------------------------
    now = datetime.now(timezone.utc)

    header = [
        "[Adblock Plus 2.0]",
        f"! Version: {now.strftime('%Y%m%d%H%M')}",
        "! Title: Anti-Extremism & Anti-Semitism Blocklist",
        f"! Last modified: {now.strftime('%d %b %Y %H:%M UTC')}",
        "! Expires: 1 days (update frequency)",
        "! Homepage: https://github.com/its-tujo/Blocklist-for-Far-Right-and-Anti-Semitic-Websites",
        "! License: The Unlicense",
        "!",
        "! This file is automatically generated.",
        "! Do not edit manually.",
        "!",
        f"! Total domains: {len(all_domains)}",
        "!",
        "! Files:",
        "! - BlockList.txt",
        "! - uBlock.txt",
        "! - LeechBlock.txt",
        "!",
        "! ---------------------- Filter List ----------------------!",
        ""
    ]

    write_file("uBlock.txt", header + ublock_rules)

    # -------------------------
    # LeechBlock
    # -------------------------
    write_file("LeechBlock.txt", leechblock)

    # -------------------------
    # Report
    # -------------------------
    report = [
        "# Blocklist Sync Report",
        f"Generated: {now.isoformat()} UTC",
        "",
        "## Summary",
        f"- Total domains: {len(all_domains)}",
        f"- Added: {len(added)}",
        f"- Removed: {len(removed)}",
        ""
    ]

    if added:
        report.append("## Added")
        report.extend([f"- {d}" for d in added])
        report.append("")

    if removed:
        report.append("## Removed")
        report.extend([f"- {d}" for d in removed])
        report.append("")

    write_file("report.md", report)
    write_file("step_summary.md", report)

    # console output (GitHub Actions log)
    print("\n=== DIFF ===")
    print(f"Added: {len(added)}")
    print(f"Removed: {len(removed)}")


if __name__ == "__main__":
    main()
